### ISSUE TITLE
Bytecode not visible for deployed contract 

### ISSUE THREAD

**Issue by nickhere432** [Sekin/ethereum-bytecode-deployment#1]
I tried to deploy the contract using deployBytecode function, the contract gets deployed but only 0x is showing as bytecode. Pls, help to solve this issue.  

Bytecode deployment contract - https://testnet.bscscan.com/address/0x5407cd23dd18a8f5b7347e9d05c914042fea69a7
Contract deployed using deployBytecode function - https://testnet.bscscan.com/address/0x6c1f329bde7674cd41fe62c5de4605333eb64de8

![image](https://user-images.githubusercontent.com/96626691/147406878-2bacf2fb-da9d-4e62-9923-321348f9d7c8.png)

**Comment by Sekin** [comment]
@nickhere432 Hi Nick! Sorry for replying three months later. You have probably moved on since. I have not done anything with smart contracts for a long time. However, I will look into it.

**Comment by Sekin** [comment]
@nickhere432 Hi Nick! You deployed the contract on the Binance Smart Chain's test network. I used Remix with the JavaScript VM. The following steps worked fine:

1. Compiled and deployed **DeployBytecode** contract.
2. Compiled second contract:
`pragma solidity ^0.4.11;
contract C {
  uint256 a;
  function setA(uint256 _a) {
    a = _a;
  }
  function getA() returns(uint256) {
    return a;
  }
}`
3. Used second contract's byte code to deploy with DeployBytecode method.
4. Used the output address in Remix's **At address** option.
5. Interacted with the contract.

Do you know what methods the contract you deployed has?
